name: Branch Protection

on:
  # Run on repository creation and manual triggers
  create:
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up branch protection
        uses: softprops/ghaction-branch-protection@v1
        with:
          branches: 'main'
          strict: true
          enforce_admins: false
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: true
          require_status_checks: true
          required_status_checks_contexts: >-
            ["Security Scan / Analyze (javascript)", 
             "Security Scan / Analyze (typescript)", 
             "Security Scan / Dependency Scan"]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 