[build]
  command = "NODE_ENV=production npm ci && npm run build:netlify"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':(exclude)src/components/ui/toggle.tsx' ':(exclude)src/components/ui/toggle-group.tsx'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"
    Content-Security-Policy = """
      default-src 'self' https://*.supabase.co;
      script-src 'self' 'unsafe-inline' 'unsafe-eval';
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      img-src 'self' data: blob: https://*;
      font-src 'self' https://fonts.gstatic.com;
      connect-src 'self' https://*.supabase.co wss://*.supabase.co https://api.openai.com;
      frame-ancestors 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18.18.0"
  NPM_VERSION = "9.6.0"
  VITE_SUPABASE_URL = "https://ekpiqiatfwozmepkgbbe.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrcGlxaWF0Zndvem1lcGtnYmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2OTc3MzYsImV4cCI6MjA1NTI3MzczNn0.qPD707Lp5FiAjlQwfC1bbG-O2WuNUe_ZYRjox6Dmb-Y"
  # We'll install necessary dependencies in the build script
  SKIP_INSTALL_DEPS = "false"
  # Setting compiler options directly to avoid conflicts
  TS_NODE_COMPILER_OPTIONS = "{\"module\":\"commonjs\",\"target\":\"es2019\",\"noEmit\":false}"
  # Vite specific environment variables
  VITE_BUILD_TARGET = "es2019"
  VITE_DROP_CONSOLE = "true"
  VITE_BUILD_MINIFY = "terser"

[functions]
  node_bundler = "esbuild"
