[build]
  command = "npm i -g pnpm && pnpm install --shamefully-hoist && pnpm build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=3600"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  CI = "true"
  ROLLUP_SKIP_NODE_RESOLUTION = "true" 